// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: css/base.proto

package com.fingo.littlec.proto.css;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.base.UserInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string appkey = 2;</code>
     */
    java.lang.String getAppkey();
    /**
     * <code>optional string appkey = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <code>optional string nick = 3;</code>
     */
    java.lang.String getNick();
    /**
     * <code>optional string nick = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <code>optional string phone = 4;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional string original_link = 5;</code>
     */
    java.lang.String getOriginalLink();
    /**
     * <code>optional string original_link = 5;</code>
     */
    com.google.protobuf.ByteString
        getOriginalLinkBytes();

    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    java.lang.String getThumbnailLink();
    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    com.google.protobuf.ByteString
        getThumbnailLinkBytes();

    /**
     * <code>optional uint64 created = 7;</code>
     */
    long getCreated();

    /**
     * <code>optional uint64 modified = 8;</code>
     */
    long getModified();
  }
  /**
   * Protobuf type {@code css.base.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageLite<
          UserInfo, UserInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:css.base.UserInfo)
      UserInfoOrBuilder {
    private UserInfo() {
      username_ = "";
      appkey_ = "";
      nick_ = "";
      phone_ = "";
      originalLink_ = "";
      thumbnailLink_ = "";
    }
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.String username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      return username_;
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(username_);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    private void setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      username_ = value;
    }
    /**
     * <code>optional string username = 1;</code>
     */
    private void clearUsername() {

      username_ = getDefaultInstance().getUsername();
    }
    /**
     * <code>optional string username = 1;</code>
     */
    private void setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      username_ = value.toStringUtf8();
    }

    public static final int APPKEY_FIELD_NUMBER = 2;
    private java.lang.String appkey_;
    /**
     * <code>optional string appkey = 2;</code>
     */
    public java.lang.String getAppkey() {
      return appkey_;
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appkey_);
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    private void setAppkey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      appkey_ = value;
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    private void clearAppkey() {

      appkey_ = getDefaultInstance().getAppkey();
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    private void setAppkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      appkey_ = value.toStringUtf8();
    }

    public static final int NICK_FIELD_NUMBER = 3;
    private java.lang.String nick_;
    /**
     * <code>optional string nick = 3;</code>
     */
    public java.lang.String getNick() {
      return nick_;
    }
    /**
     * <code>optional string nick = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nick_);
    }
    /**
     * <code>optional string nick = 3;</code>
     */
    private void setNick(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nick_ = value;
    }
    /**
     * <code>optional string nick = 3;</code>
     */
    private void clearNick() {

      nick_ = getDefaultInstance().getNick();
    }
    /**
     * <code>optional string nick = 3;</code>
     */
    private void setNickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      nick_ = value.toStringUtf8();
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    private java.lang.String phone_;
    /**
     * <code>optional string phone = 4;</code>
     */
    public java.lang.String getPhone() {
      return phone_;
    }
    /**
     * <code>optional string phone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phone_);
    }
    /**
     * <code>optional string phone = 4;</code>
     */
    private void setPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      phone_ = value;
    }
    /**
     * <code>optional string phone = 4;</code>
     */
    private void clearPhone() {

      phone_ = getDefaultInstance().getPhone();
    }
    /**
     * <code>optional string phone = 4;</code>
     */
    private void setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      phone_ = value.toStringUtf8();
    }

    public static final int ORIGINAL_LINK_FIELD_NUMBER = 5;
    private java.lang.String originalLink_;
    /**
     * <code>optional string original_link = 5;</code>
     */
    public java.lang.String getOriginalLink() {
      return originalLink_;
    }
    /**
     * <code>optional string original_link = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOriginalLinkBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(originalLink_);
    }
    /**
     * <code>optional string original_link = 5;</code>
     */
    private void setOriginalLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      originalLink_ = value;
    }
    /**
     * <code>optional string original_link = 5;</code>
     */
    private void clearOriginalLink() {

      originalLink_ = getDefaultInstance().getOriginalLink();
    }
    /**
     * <code>optional string original_link = 5;</code>
     */
    private void setOriginalLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      originalLink_ = value.toStringUtf8();
    }

    public static final int THUMBNAIL_LINK_FIELD_NUMBER = 6;
    private java.lang.String thumbnailLink_;
    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    public java.lang.String getThumbnailLink() {
      return thumbnailLink_;
    }
    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    public com.google.protobuf.ByteString
        getThumbnailLinkBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(thumbnailLink_);
    }
    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    private void setThumbnailLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      thumbnailLink_ = value;
    }
    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    private void clearThumbnailLink() {

      thumbnailLink_ = getDefaultInstance().getThumbnailLink();
    }
    /**
     * <code>optional string thumbnail_link = 6;</code>
     */
    private void setThumbnailLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      thumbnailLink_ = value.toStringUtf8();
    }

    public static final int CREATED_FIELD_NUMBER = 7;
    private long created_;
    /**
     * <code>optional uint64 created = 7;</code>
     */
    public long getCreated() {
      return created_;
    }
    /**
     * <code>optional uint64 created = 7;</code>
     */
    private void setCreated(long value) {

      created_ = value;
    }
    /**
     * <code>optional uint64 created = 7;</code>
     */
    private void clearCreated() {

      created_ = 0L;
    }

    public static final int MODIFIED_FIELD_NUMBER = 8;
    private long modified_;
    /**
     * <code>optional uint64 modified = 8;</code>
     */
    public long getModified() {
      return modified_;
    }
    /**
     * <code>optional uint64 modified = 8;</code>
     */
    private void setModified(long value) {

      modified_ = value;
    }
    /**
     * <code>optional uint64 modified = 8;</code>
     */
    private void clearModified() {

      modified_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!username_.isEmpty()) {
        output.writeString(1, getUsername());
      }
      if (!appkey_.isEmpty()) {
        output.writeString(2, getAppkey());
      }
      if (!nick_.isEmpty()) {
        output.writeString(3, getNick());
      }
      if (!phone_.isEmpty()) {
        output.writeString(4, getPhone());
      }
      if (!originalLink_.isEmpty()) {
        output.writeString(5, getOriginalLink());
      }
      if (!thumbnailLink_.isEmpty()) {
        output.writeString(6, getThumbnailLink());
      }
      if (created_ != 0L) {
        output.writeUInt64(7, created_);
      }
      if (modified_ != 0L) {
        output.writeUInt64(8, modified_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!username_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUsername());
      }
      if (!appkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getAppkey());
      }
      if (!nick_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNick());
      }
      if (!phone_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getPhone());
      }
      if (!originalLink_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getOriginalLink());
      }
      if (!thumbnailLink_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getThumbnailLink());
      }
      if (created_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, created_);
      }
      if (modified_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, modified_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Base.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code css.base.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UserInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.base.UserInfo)
        com.fingo.littlec.proto.css.Base.UserInfoOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Base.UserInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        return instance.getUsername();
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        return instance.getUsernameBytes();
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        copyOnWrite();
        instance.setUsername(value);
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        copyOnWrite();
        instance.clearUsername();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUsernameBytes(value);
        return this;
      }

      /**
       * <code>optional string appkey = 2;</code>
       */
      public java.lang.String getAppkey() {
        return instance.getAppkey();
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        return instance.getAppkeyBytes();
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public Builder setAppkey(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppkey(value);
        return this;
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public Builder clearAppkey() {
        copyOnWrite();
        instance.clearAppkey();
        return this;
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppkeyBytes(value);
        return this;
      }

      /**
       * <code>optional string nick = 3;</code>
       */
      public java.lang.String getNick() {
        return instance.getNick();
      }
      /**
       * <code>optional string nick = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        return instance.getNickBytes();
      }
      /**
       * <code>optional string nick = 3;</code>
       */
      public Builder setNick(
          java.lang.String value) {
        copyOnWrite();
        instance.setNick(value);
        return this;
      }
      /**
       * <code>optional string nick = 3;</code>
       */
      public Builder clearNick() {
        copyOnWrite();
        instance.clearNick();
        return this;
      }
      /**
       * <code>optional string nick = 3;</code>
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNickBytes(value);
        return this;
      }

      /**
       * <code>optional string phone = 4;</code>
       */
      public java.lang.String getPhone() {
        return instance.getPhone();
      }
      /**
       * <code>optional string phone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        return instance.getPhoneBytes();
      }
      /**
       * <code>optional string phone = 4;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        copyOnWrite();
        instance.setPhone(value);
        return this;
      }
      /**
       * <code>optional string phone = 4;</code>
       */
      public Builder clearPhone() {
        copyOnWrite();
        instance.clearPhone();
        return this;
      }
      /**
       * <code>optional string phone = 4;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneBytes(value);
        return this;
      }

      /**
       * <code>optional string original_link = 5;</code>
       */
      public java.lang.String getOriginalLink() {
        return instance.getOriginalLink();
      }
      /**
       * <code>optional string original_link = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOriginalLinkBytes() {
        return instance.getOriginalLinkBytes();
      }
      /**
       * <code>optional string original_link = 5;</code>
       */
      public Builder setOriginalLink(
          java.lang.String value) {
        copyOnWrite();
        instance.setOriginalLink(value);
        return this;
      }
      /**
       * <code>optional string original_link = 5;</code>
       */
      public Builder clearOriginalLink() {
        copyOnWrite();
        instance.clearOriginalLink();
        return this;
      }
      /**
       * <code>optional string original_link = 5;</code>
       */
      public Builder setOriginalLinkBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOriginalLinkBytes(value);
        return this;
      }

      /**
       * <code>optional string thumbnail_link = 6;</code>
       */
      public java.lang.String getThumbnailLink() {
        return instance.getThumbnailLink();
      }
      /**
       * <code>optional string thumbnail_link = 6;</code>
       */
      public com.google.protobuf.ByteString
          getThumbnailLinkBytes() {
        return instance.getThumbnailLinkBytes();
      }
      /**
       * <code>optional string thumbnail_link = 6;</code>
       */
      public Builder setThumbnailLink(
          java.lang.String value) {
        copyOnWrite();
        instance.setThumbnailLink(value);
        return this;
      }
      /**
       * <code>optional string thumbnail_link = 6;</code>
       */
      public Builder clearThumbnailLink() {
        copyOnWrite();
        instance.clearThumbnailLink();
        return this;
      }
      /**
       * <code>optional string thumbnail_link = 6;</code>
       */
      public Builder setThumbnailLinkBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setThumbnailLinkBytes(value);
        return this;
      }

      /**
       * <code>optional uint64 created = 7;</code>
       */
      public long getCreated() {
        return instance.getCreated();
      }
      /**
       * <code>optional uint64 created = 7;</code>
       */
      public Builder setCreated(long value) {
        copyOnWrite();
        instance.setCreated(value);
        return this;
      }
      /**
       * <code>optional uint64 created = 7;</code>
       */
      public Builder clearCreated() {
        copyOnWrite();
        instance.clearCreated();
        return this;
      }

      /**
       * <code>optional uint64 modified = 8;</code>
       */
      public long getModified() {
        return instance.getModified();
      }
      /**
       * <code>optional uint64 modified = 8;</code>
       */
      public Builder setModified(long value) {
        copyOnWrite();
        instance.setModified(value);
        return this;
      }
      /**
       * <code>optional uint64 modified = 8;</code>
       */
      public Builder clearModified() {
        copyOnWrite();
        instance.clearModified();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.base.UserInfo)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Base.UserInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Base.UserInfo other = (com.fingo.littlec.proto.css.Base.UserInfo) arg1;
          username_ = visitor.visitString(!username_.isEmpty(), username_,
              !other.username_.isEmpty(), other.username_);
          appkey_ = visitor.visitString(!appkey_.isEmpty(), appkey_,
              !other.appkey_.isEmpty(), other.appkey_);
          nick_ = visitor.visitString(!nick_.isEmpty(), nick_,
              !other.nick_.isEmpty(), other.nick_);
          phone_ = visitor.visitString(!phone_.isEmpty(), phone_,
              !other.phone_.isEmpty(), other.phone_);
          originalLink_ = visitor.visitString(!originalLink_.isEmpty(), originalLink_,
              !other.originalLink_.isEmpty(), other.originalLink_);
          thumbnailLink_ = visitor.visitString(!thumbnailLink_.isEmpty(), thumbnailLink_,
              !other.thumbnailLink_.isEmpty(), other.thumbnailLink_);
          created_ = visitor.visitLong(created_ != 0L, created_,
              other.created_ != 0L, other.created_);
          modified_ = visitor.visitLong(modified_ != 0L, modified_,
              other.modified_ != 0L, other.modified_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  username_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  appkey_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  nick_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  phone_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  originalLink_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  thumbnailLink_ = s;
                  break;
                }
                case 56: {

                  created_ = input.readUInt64();
                  break;
                }
                case 64: {

                  modified_ = input.readUInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Base.UserInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.base.UserInfo)
    private static final com.fingo.littlec.proto.css.Base.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Base.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserInfo> PARSER;

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PaginationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.base.Pagination)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 page_size = 1;</code>
     */
    int getPageSize();

    /**
     * <code>optional int32 page_num = 2;</code>
     */
    int getPageNum();

    /**
     * <code>optional string order_str = 3;</code>
     */
    java.lang.String getOrderStr();
    /**
     * <code>optional string order_str = 3;</code>
     */
    com.google.protobuf.ByteString
        getOrderStrBytes();

    /**
     * <code>optional bool paging_switch = 4;</code>
     */
    boolean getPagingSwitch();
  }
  /**
   * <pre>
   * 分页
   * </pre>
   *
   * Protobuf type {@code css.base.Pagination}
   */
  public  static final class Pagination extends
      com.google.protobuf.GeneratedMessageLite<
          Pagination, Pagination.Builder> implements
      // @@protoc_insertion_point(message_implements:css.base.Pagination)
      PaginationOrBuilder {
    private Pagination() {
      orderStr_ = "";
    }
    public static final int PAGE_SIZE_FIELD_NUMBER = 1;
    private int pageSize_;
    /**
     * <code>optional int32 page_size = 1;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>optional int32 page_size = 1;</code>
     */
    private void setPageSize(int value) {

      pageSize_ = value;
    }
    /**
     * <code>optional int32 page_size = 1;</code>
     */
    private void clearPageSize() {

      pageSize_ = 0;
    }

    public static final int PAGE_NUM_FIELD_NUMBER = 2;
    private int pageNum_;
    /**
     * <code>optional int32 page_num = 2;</code>
     */
    public int getPageNum() {
      return pageNum_;
    }
    /**
     * <code>optional int32 page_num = 2;</code>
     */
    private void setPageNum(int value) {

      pageNum_ = value;
    }
    /**
     * <code>optional int32 page_num = 2;</code>
     */
    private void clearPageNum() {

      pageNum_ = 0;
    }

    public static final int ORDER_STR_FIELD_NUMBER = 3;
    private java.lang.String orderStr_;
    /**
     * <code>optional string order_str = 3;</code>
     */
    public java.lang.String getOrderStr() {
      return orderStr_;
    }
    /**
     * <code>optional string order_str = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrderStrBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(orderStr_);
    }
    /**
     * <code>optional string order_str = 3;</code>
     */
    private void setOrderStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      orderStr_ = value;
    }
    /**
     * <code>optional string order_str = 3;</code>
     */
    private void clearOrderStr() {

      orderStr_ = getDefaultInstance().getOrderStr();
    }
    /**
     * <code>optional string order_str = 3;</code>
     */
    private void setOrderStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      orderStr_ = value.toStringUtf8();
    }

    public static final int PAGING_SWITCH_FIELD_NUMBER = 4;
    private boolean pagingSwitch_;
    /**
     * <code>optional bool paging_switch = 4;</code>
     */
    public boolean getPagingSwitch() {
      return pagingSwitch_;
    }
    /**
     * <code>optional bool paging_switch = 4;</code>
     */
    private void setPagingSwitch(boolean value) {

      pagingSwitch_ = value;
    }
    /**
     * <code>optional bool paging_switch = 4;</code>
     */
    private void clearPagingSwitch() {

      pagingSwitch_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageSize_ != 0) {
        output.writeInt32(1, pageSize_);
      }
      if (pageNum_ != 0) {
        output.writeInt32(2, pageNum_);
      }
      if (!orderStr_.isEmpty()) {
        output.writeString(3, getOrderStr());
      }
      if (pagingSwitch_ != false) {
        output.writeBool(4, pagingSwitch_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageSize_);
      }
      if (pageNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNum_);
      }
      if (!orderStr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getOrderStr());
      }
      if (pagingSwitch_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, pagingSwitch_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.Pagination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Base.Pagination prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 分页
     * </pre>
     *
     * Protobuf type {@code css.base.Pagination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Pagination, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.base.Pagination)
        com.fingo.littlec.proto.css.Base.PaginationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Base.Pagination.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 page_size = 1;</code>
       */
      public int getPageSize() {
        return instance.getPageSize();
      }
      /**
       * <code>optional int32 page_size = 1;</code>
       */
      public Builder setPageSize(int value) {
        copyOnWrite();
        instance.setPageSize(value);
        return this;
      }
      /**
       * <code>optional int32 page_size = 1;</code>
       */
      public Builder clearPageSize() {
        copyOnWrite();
        instance.clearPageSize();
        return this;
      }

      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public int getPageNum() {
        return instance.getPageNum();
      }
      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public Builder setPageNum(int value) {
        copyOnWrite();
        instance.setPageNum(value);
        return this;
      }
      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public Builder clearPageNum() {
        copyOnWrite();
        instance.clearPageNum();
        return this;
      }

      /**
       * <code>optional string order_str = 3;</code>
       */
      public java.lang.String getOrderStr() {
        return instance.getOrderStr();
      }
      /**
       * <code>optional string order_str = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOrderStrBytes() {
        return instance.getOrderStrBytes();
      }
      /**
       * <code>optional string order_str = 3;</code>
       */
      public Builder setOrderStr(
          java.lang.String value) {
        copyOnWrite();
        instance.setOrderStr(value);
        return this;
      }
      /**
       * <code>optional string order_str = 3;</code>
       */
      public Builder clearOrderStr() {
        copyOnWrite();
        instance.clearOrderStr();
        return this;
      }
      /**
       * <code>optional string order_str = 3;</code>
       */
      public Builder setOrderStrBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOrderStrBytes(value);
        return this;
      }

      /**
       * <code>optional bool paging_switch = 4;</code>
       */
      public boolean getPagingSwitch() {
        return instance.getPagingSwitch();
      }
      /**
       * <code>optional bool paging_switch = 4;</code>
       */
      public Builder setPagingSwitch(boolean value) {
        copyOnWrite();
        instance.setPagingSwitch(value);
        return this;
      }
      /**
       * <code>optional bool paging_switch = 4;</code>
       */
      public Builder clearPagingSwitch() {
        copyOnWrite();
        instance.clearPagingSwitch();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.base.Pagination)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Base.Pagination();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Base.Pagination other = (com.fingo.littlec.proto.css.Base.Pagination) arg1;
          pageSize_ = visitor.visitInt(pageSize_ != 0, pageSize_,
              other.pageSize_ != 0, other.pageSize_);
          pageNum_ = visitor.visitInt(pageNum_ != 0, pageNum_,
              other.pageNum_ != 0, other.pageNum_);
          orderStr_ = visitor.visitString(!orderStr_.isEmpty(), orderStr_,
              !other.orderStr_.isEmpty(), other.orderStr_);
          pagingSwitch_ = visitor.visitBoolean(pagingSwitch_ != false, pagingSwitch_,
              other.pagingSwitch_ != false, other.pagingSwitch_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  pageSize_ = input.readInt32();
                  break;
                }
                case 16: {

                  pageNum_ = input.readInt32();
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  orderStr_ = s;
                  break;
                }
                case 32: {

                  pagingSwitch_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Base.Pagination.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.base.Pagination)
    private static final com.fingo.littlec.proto.css.Base.Pagination DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pagination();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Base.Pagination getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Pagination> PARSER;

    public static com.google.protobuf.Parser<Pagination> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MobileBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.base.MobileBase)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    java.lang.String getSdkVersion();
    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdkVersionBytes();

    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    int getLanguageTypeValue();
    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    com.fingo.littlec.proto.css.Enum.ELanguageType getLanguageType();

    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    int getNetTypeValue();
    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    com.fingo.littlec.proto.css.Enum.ENetworkType getNetType();

    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    java.lang.String getOsVersion();
    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    com.google.protobuf.ByteString
        getOsVersionBytes();

    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    int getClientTypeValue();
    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    com.fingo.littlec.proto.css.Enum.EClientType getClientType();

    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    java.lang.String getDevice();
    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    com.google.protobuf.ByteString
        getDeviceBytes();

    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    java.lang.String getImei();
    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();
  }
  /**
   * Protobuf type {@code css.base.MobileBase}
   */
  public  static final class MobileBase extends
      com.google.protobuf.GeneratedMessageLite<
          MobileBase, MobileBase.Builder> implements
      // @@protoc_insertion_point(message_implements:css.base.MobileBase)
      MobileBaseOrBuilder {
    private MobileBase() {
      sdkVersion_ = "";
      osVersion_ = "";
      device_ = "";
      imei_ = "";
    }
    public static final int SDK_VERSION_FIELD_NUMBER = 1;
    private java.lang.String sdkVersion_;
    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    public java.lang.String getSdkVersion() {
      return sdkVersion_;
    }
    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdkVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sdkVersion_);
    }
    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    private void setSdkVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      sdkVersion_ = value;
    }
    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    private void clearSdkVersion() {

      sdkVersion_ = getDefaultInstance().getSdkVersion();
    }
    /**
     * <pre>
     * sdk 版本号
     * </pre>
     *
     * <code>optional string sdk_version = 1;</code>
     */
    private void setSdkVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      sdkVersion_ = value.toStringUtf8();
    }

    public static final int LANGUAGE_TYPE_FIELD_NUMBER = 2;
    private int languageType_;
    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    public int getLanguageTypeValue() {
      return languageType_;
    }
    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    public com.fingo.littlec.proto.css.Enum.ELanguageType getLanguageType() {
      com.fingo.littlec.proto.css.Enum.ELanguageType result = com.fingo.littlec.proto.css.Enum.ELanguageType.forNumber(languageType_);
      return result == null ? com.fingo.littlec.proto.css.Enum.ELanguageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    private void setLanguageTypeValue(int value) {
        languageType_ = value;
    }
    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    private void setLanguageType(com.fingo.littlec.proto.css.Enum.ELanguageType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      languageType_ = value.getNumber();
    }
    /**
     * <pre>
     * 语言类型
     * </pre>
     *
     * <code>optional .css.enum.ELanguageType language_type = 2;</code>
     */
    private void clearLanguageType() {

      languageType_ = 0;
    }

    public static final int NET_TYPE_FIELD_NUMBER = 3;
    private int netType_;
    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    public int getNetTypeValue() {
      return netType_;
    }
    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    public com.fingo.littlec.proto.css.Enum.ENetworkType getNetType() {
      com.fingo.littlec.proto.css.Enum.ENetworkType result = com.fingo.littlec.proto.css.Enum.ENetworkType.forNumber(netType_);
      return result == null ? com.fingo.littlec.proto.css.Enum.ENetworkType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    private void setNetTypeValue(int value) {
        netType_ = value;
    }
    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    private void setNetType(com.fingo.littlec.proto.css.Enum.ENetworkType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      netType_ = value.getNumber();
    }
    /**
     * <pre>
     * 网络类型
     * </pre>
     *
     * <code>optional .css.enum.ENetworkType net_type = 3;</code>
     */
    private void clearNetType() {

      netType_ = 0;
    }

    public static final int OS_VERSION_FIELD_NUMBER = 4;
    private java.lang.String osVersion_;
    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    public java.lang.String getOsVersion() {
      return osVersion_;
    }
    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(osVersion_);
    }
    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    private void setOsVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      osVersion_ = value;
    }
    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    private void clearOsVersion() {

      osVersion_ = getDefaultInstance().getOsVersion();
    }
    /**
     * <pre>
     *操作系统版本
     * </pre>
     *
     * <code>optional string os_version = 4;</code>
     */
    private void setOsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      osVersion_ = value.toStringUtf8();
    }

    public static final int CLIENT_TYPE_FIELD_NUMBER = 5;
    private int clientType_;
    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    public int getClientTypeValue() {
      return clientType_;
    }
    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    public com.fingo.littlec.proto.css.Enum.EClientType getClientType() {
      com.fingo.littlec.proto.css.Enum.EClientType result = com.fingo.littlec.proto.css.Enum.EClientType.forNumber(clientType_);
      return result == null ? com.fingo.littlec.proto.css.Enum.EClientType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    private void setClientTypeValue(int value) {
        clientType_ = value;
    }
    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    private void setClientType(com.fingo.littlec.proto.css.Enum.EClientType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      clientType_ = value.getNumber();
    }
    /**
     * <pre>
     * 设备类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType client_type = 5;</code>
     */
    private void clearClientType() {

      clientType_ = 0;
    }

    public static final int DEVICE_FIELD_NUMBER = 6;
    private java.lang.String device_;
    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    public java.lang.String getDevice() {
      return device_;
    }
    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(device_);
    }
    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    private void setDevice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      device_ = value;
    }
    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    private void clearDevice() {

      device_ = getDefaultInstance().getDevice();
    }
    /**
     * <pre>
     * 设备型号
     * </pre>
     *
     * <code>optional string device = 6;</code>
     */
    private void setDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      device_ = value.toStringUtf8();
    }

    public static final int IMEI_FIELD_NUMBER = 7;
    private java.lang.String imei_;
    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    public java.lang.String getImei() {
      return imei_;
    }
    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(imei_);
    }
    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    private void setImei(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      imei_ = value;
    }
    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    private void clearImei() {

      imei_ = getDefaultInstance().getImei();
    }
    /**
     * <pre>
     * 国际移动设备识别码
     * </pre>
     *
     * <code>optional string imei = 7;</code>
     */
    private void setImeiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      imei_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sdkVersion_.isEmpty()) {
        output.writeString(1, getSdkVersion());
      }
      if (languageType_ != com.fingo.littlec.proto.css.Enum.ELanguageType.CHINESE.getNumber()) {
        output.writeEnum(2, languageType_);
      }
      if (netType_ != com.fingo.littlec.proto.css.Enum.ENetworkType.WIFI.getNumber()) {
        output.writeEnum(3, netType_);
      }
      if (!osVersion_.isEmpty()) {
        output.writeString(4, getOsVersion());
      }
      if (clientType_ != com.fingo.littlec.proto.css.Enum.EClientType.UNKNOWN.getNumber()) {
        output.writeEnum(5, clientType_);
      }
      if (!device_.isEmpty()) {
        output.writeString(6, getDevice());
      }
      if (!imei_.isEmpty()) {
        output.writeString(7, getImei());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!sdkVersion_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSdkVersion());
      }
      if (languageType_ != com.fingo.littlec.proto.css.Enum.ELanguageType.CHINESE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, languageType_);
      }
      if (netType_ != com.fingo.littlec.proto.css.Enum.ENetworkType.WIFI.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, netType_);
      }
      if (!osVersion_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getOsVersion());
      }
      if (clientType_ != com.fingo.littlec.proto.css.Enum.EClientType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, clientType_);
      }
      if (!device_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getDevice());
      }
      if (!imei_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getImei());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Base.MobileBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Base.MobileBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code css.base.MobileBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          MobileBase, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.base.MobileBase)
        com.fingo.littlec.proto.css.Base.MobileBaseOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Base.MobileBase.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * sdk 版本号
       * </pre>
       *
       * <code>optional string sdk_version = 1;</code>
       */
      public java.lang.String getSdkVersion() {
        return instance.getSdkVersion();
      }
      /**
       * <pre>
       * sdk 版本号
       * </pre>
       *
       * <code>optional string sdk_version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdkVersionBytes() {
        return instance.getSdkVersionBytes();
      }
      /**
       * <pre>
       * sdk 版本号
       * </pre>
       *
       * <code>optional string sdk_version = 1;</code>
       */
      public Builder setSdkVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setSdkVersion(value);
        return this;
      }
      /**
       * <pre>
       * sdk 版本号
       * </pre>
       *
       * <code>optional string sdk_version = 1;</code>
       */
      public Builder clearSdkVersion() {
        copyOnWrite();
        instance.clearSdkVersion();
        return this;
      }
      /**
       * <pre>
       * sdk 版本号
       * </pre>
       *
       * <code>optional string sdk_version = 1;</code>
       */
      public Builder setSdkVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSdkVersionBytes(value);
        return this;
      }

      /**
       * <pre>
       * 语言类型
       * </pre>
       *
       * <code>optional .css.enum.ELanguageType language_type = 2;</code>
       */
      public int getLanguageTypeValue() {
        return instance.getLanguageTypeValue();
      }
      /**
       * <pre>
       * 语言类型
       * </pre>
       *
       * <code>optional .css.enum.ELanguageType language_type = 2;</code>
       */
      public Builder setLanguageTypeValue(int value) {
        copyOnWrite();
        instance.setLanguageTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * 语言类型
       * </pre>
       *
       * <code>optional .css.enum.ELanguageType language_type = 2;</code>
       */
      public com.fingo.littlec.proto.css.Enum.ELanguageType getLanguageType() {
        return instance.getLanguageType();
      }
      /**
       * <pre>
       * 语言类型
       * </pre>
       *
       * <code>optional .css.enum.ELanguageType language_type = 2;</code>
       */
      public Builder setLanguageType(com.fingo.littlec.proto.css.Enum.ELanguageType value) {
        copyOnWrite();
        instance.setLanguageType(value);
        return this;
      }
      /**
       * <pre>
       * 语言类型
       * </pre>
       *
       * <code>optional .css.enum.ELanguageType language_type = 2;</code>
       */
      public Builder clearLanguageType() {
        copyOnWrite();
        instance.clearLanguageType();
        return this;
      }

      /**
       * <pre>
       * 网络类型
       * </pre>
       *
       * <code>optional .css.enum.ENetworkType net_type = 3;</code>
       */
      public int getNetTypeValue() {
        return instance.getNetTypeValue();
      }
      /**
       * <pre>
       * 网络类型
       * </pre>
       *
       * <code>optional .css.enum.ENetworkType net_type = 3;</code>
       */
      public Builder setNetTypeValue(int value) {
        copyOnWrite();
        instance.setNetTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * 网络类型
       * </pre>
       *
       * <code>optional .css.enum.ENetworkType net_type = 3;</code>
       */
      public com.fingo.littlec.proto.css.Enum.ENetworkType getNetType() {
        return instance.getNetType();
      }
      /**
       * <pre>
       * 网络类型
       * </pre>
       *
       * <code>optional .css.enum.ENetworkType net_type = 3;</code>
       */
      public Builder setNetType(com.fingo.littlec.proto.css.Enum.ENetworkType value) {
        copyOnWrite();
        instance.setNetType(value);
        return this;
      }
      /**
       * <pre>
       * 网络类型
       * </pre>
       *
       * <code>optional .css.enum.ENetworkType net_type = 3;</code>
       */
      public Builder clearNetType() {
        copyOnWrite();
        instance.clearNetType();
        return this;
      }

      /**
       * <pre>
       *操作系统版本
       * </pre>
       *
       * <code>optional string os_version = 4;</code>
       */
      public java.lang.String getOsVersion() {
        return instance.getOsVersion();
      }
      /**
       * <pre>
       *操作系统版本
       * </pre>
       *
       * <code>optional string os_version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOsVersionBytes() {
        return instance.getOsVersionBytes();
      }
      /**
       * <pre>
       *操作系统版本
       * </pre>
       *
       * <code>optional string os_version = 4;</code>
       */
      public Builder setOsVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setOsVersion(value);
        return this;
      }
      /**
       * <pre>
       *操作系统版本
       * </pre>
       *
       * <code>optional string os_version = 4;</code>
       */
      public Builder clearOsVersion() {
        copyOnWrite();
        instance.clearOsVersion();
        return this;
      }
      /**
       * <pre>
       *操作系统版本
       * </pre>
       *
       * <code>optional string os_version = 4;</code>
       */
      public Builder setOsVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOsVersionBytes(value);
        return this;
      }

      /**
       * <pre>
       * 设备类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType client_type = 5;</code>
       */
      public int getClientTypeValue() {
        return instance.getClientTypeValue();
      }
      /**
       * <pre>
       * 设备类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType client_type = 5;</code>
       */
      public Builder setClientTypeValue(int value) {
        copyOnWrite();
        instance.setClientTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * 设备类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType client_type = 5;</code>
       */
      public com.fingo.littlec.proto.css.Enum.EClientType getClientType() {
        return instance.getClientType();
      }
      /**
       * <pre>
       * 设备类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType client_type = 5;</code>
       */
      public Builder setClientType(com.fingo.littlec.proto.css.Enum.EClientType value) {
        copyOnWrite();
        instance.setClientType(value);
        return this;
      }
      /**
       * <pre>
       * 设备类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType client_type = 5;</code>
       */
      public Builder clearClientType() {
        copyOnWrite();
        instance.clearClientType();
        return this;
      }

      /**
       * <pre>
       * 设备型号
       * </pre>
       *
       * <code>optional string device = 6;</code>
       */
      public java.lang.String getDevice() {
        return instance.getDevice();
      }
      /**
       * <pre>
       * 设备型号
       * </pre>
       *
       * <code>optional string device = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceBytes() {
        return instance.getDeviceBytes();
      }
      /**
       * <pre>
       * 设备型号
       * </pre>
       *
       * <code>optional string device = 6;</code>
       */
      public Builder setDevice(
          java.lang.String value) {
        copyOnWrite();
        instance.setDevice(value);
        return this;
      }
      /**
       * <pre>
       * 设备型号
       * </pre>
       *
       * <code>optional string device = 6;</code>
       */
      public Builder clearDevice() {
        copyOnWrite();
        instance.clearDevice();
        return this;
      }
      /**
       * <pre>
       * 设备型号
       * </pre>
       *
       * <code>optional string device = 6;</code>
       */
      public Builder setDeviceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceBytes(value);
        return this;
      }

      /**
       * <pre>
       * 国际移动设备识别码
       * </pre>
       *
       * <code>optional string imei = 7;</code>
       */
      public java.lang.String getImei() {
        return instance.getImei();
      }
      /**
       * <pre>
       * 国际移动设备识别码
       * </pre>
       *
       * <code>optional string imei = 7;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        return instance.getImeiBytes();
      }
      /**
       * <pre>
       * 国际移动设备识别码
       * </pre>
       *
       * <code>optional string imei = 7;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        copyOnWrite();
        instance.setImei(value);
        return this;
      }
      /**
       * <pre>
       * 国际移动设备识别码
       * </pre>
       *
       * <code>optional string imei = 7;</code>
       */
      public Builder clearImei() {
        copyOnWrite();
        instance.clearImei();
        return this;
      }
      /**
       * <pre>
       * 国际移动设备识别码
       * </pre>
       *
       * <code>optional string imei = 7;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setImeiBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.base.MobileBase)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Base.MobileBase();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Base.MobileBase other = (com.fingo.littlec.proto.css.Base.MobileBase) arg1;
          sdkVersion_ = visitor.visitString(!sdkVersion_.isEmpty(), sdkVersion_,
              !other.sdkVersion_.isEmpty(), other.sdkVersion_);
          languageType_ = visitor.visitInt(languageType_ != 0, languageType_,    other.languageType_ != 0, other.languageType_);
          netType_ = visitor.visitInt(netType_ != 0, netType_,    other.netType_ != 0, other.netType_);
          osVersion_ = visitor.visitString(!osVersion_.isEmpty(), osVersion_,
              !other.osVersion_.isEmpty(), other.osVersion_);
          clientType_ = visitor.visitInt(clientType_ != 0, clientType_,    other.clientType_ != 0, other.clientType_);
          device_ = visitor.visitString(!device_.isEmpty(), device_,
              !other.device_.isEmpty(), other.device_);
          imei_ = visitor.visitString(!imei_.isEmpty(), imei_,
              !other.imei_.isEmpty(), other.imei_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  sdkVersion_ = s;
                  break;
                }
                case 16: {
                  int rawValue = input.readEnum();

                  languageType_ = rawValue;
                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  netType_ = rawValue;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  osVersion_ = s;
                  break;
                }
                case 40: {
                  int rawValue = input.readEnum();

                  clientType_ = rawValue;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  device_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  imei_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Base.MobileBase.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.base.MobileBase)
    private static final com.fingo.littlec.proto.css.Base.MobileBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MobileBase();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Base.MobileBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MobileBase> PARSER;

    public static com.google.protobuf.Parser<MobileBase> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
