// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: css/enum.proto

package com.fingo.littlec.proto.css;

public final class Enum {
  private Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code css.enum.EEnable}
   */
  public enum EEnable
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>DISABLED = 0;</code>
     */
    DISABLED(0),
    /**
     * <code>ENABLED = 1;</code>
     */
    ENABLED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DISABLED = 0;</code>
     */
    public static final int DISABLED_VALUE = 0;
    /**
     * <code>ENABLED = 1;</code>
     */
    public static final int ENABLED_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EEnable valueOf(int value) {
      return forNumber(value);
    }

    public static EEnable forNumber(int value) {
      switch (value) {
        case 0: return DISABLED;
        case 1: return ENABLED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EEnable>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EEnable> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EEnable>() {
            public EEnable findValueByNumber(int number) {
              return EEnable.forNumber(number);
            }
          };

    private final int value;

    private EEnable(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.EEnable)
  }

  /**
   * <pre>
   * 鸡毛信是否已读
   * </pre>
   *
   * Protobuf enum {@code css.enum.EReaded}
   */
  public enum EReaded
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNREADED = 0;</code>
     */
    UNREADED(0),
    /**
     * <code>READED = 1;</code>
     */
    READED(1),
    /**
     * <code>SENDED = 2;</code>
     */
    SENDED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNREADED = 0;</code>
     */
    public static final int UNREADED_VALUE = 0;
    /**
     * <code>READED = 1;</code>
     */
    public static final int READED_VALUE = 1;
    /**
     * <code>SENDED = 2;</code>
     */
    public static final int SENDED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EReaded valueOf(int value) {
      return forNumber(value);
    }

    public static EReaded forNumber(int value) {
      switch (value) {
        case 0: return UNREADED;
        case 1: return READED;
        case 2: return SENDED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EReaded>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EReaded> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EReaded>() {
            public EReaded findValueByNumber(int number) {
              return EReaded.forNumber(number);
            }
          };

    private final int value;

    private EReaded(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.EReaded)
  }

  /**
   * Protobuf enum {@code css.enum.EClientType}
   */
  public enum EClientType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>IOS = 1;</code>
     */
    IOS(1),
    /**
     * <code>ANDROID = 2;</code>
     */
    ANDROID(2),
    /**
     * <code>WEB = 3;</code>
     */
    WEB(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>IOS = 1;</code>
     */
    public static final int IOS_VALUE = 1;
    /**
     * <code>ANDROID = 2;</code>
     */
    public static final int ANDROID_VALUE = 2;
    /**
     * <code>WEB = 3;</code>
     */
    public static final int WEB_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EClientType valueOf(int value) {
      return forNumber(value);
    }

    public static EClientType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return IOS;
        case 2: return ANDROID;
        case 3: return WEB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EClientType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EClientType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EClientType>() {
            public EClientType findValueByNumber(int number) {
              return EClientType.forNumber(number);
            }
          };

    private final int value;

    private EClientType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.EClientType)
  }

  /**
   * Protobuf enum {@code css.enum.ENetworkType}
   */
  public enum ENetworkType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>WIFI = 0;</code>
     */
    WIFI(0),
    /**
     * <code>M4G = 1;</code>
     */
    M4G(1),
    /**
     * <code>M2G = 2;</code>
     */
    M2G(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WIFI = 0;</code>
     */
    public static final int WIFI_VALUE = 0;
    /**
     * <code>M4G = 1;</code>
     */
    public static final int M4G_VALUE = 1;
    /**
     * <code>M2G = 2;</code>
     */
    public static final int M2G_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ENetworkType valueOf(int value) {
      return forNumber(value);
    }

    public static ENetworkType forNumber(int value) {
      switch (value) {
        case 0: return WIFI;
        case 1: return M4G;
        case 2: return M2G;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ENetworkType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ENetworkType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ENetworkType>() {
            public ENetworkType findValueByNumber(int number) {
              return ENetworkType.forNumber(number);
            }
          };

    private final int value;

    private ENetworkType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.ENetworkType)
  }

  /**
   * Protobuf enum {@code css.enum.ELanguageType}
   */
  public enum ELanguageType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CHINESE = 0;</code>
     */
    CHINESE(0),
    /**
     * <code>ENGLISH = 1;</code>
     */
    ENGLISH(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CHINESE = 0;</code>
     */
    public static final int CHINESE_VALUE = 0;
    /**
     * <code>ENGLISH = 1;</code>
     */
    public static final int ENGLISH_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ELanguageType valueOf(int value) {
      return forNumber(value);
    }

    public static ELanguageType forNumber(int value) {
      switch (value) {
        case 0: return CHINESE;
        case 1: return ENGLISH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ELanguageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ELanguageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ELanguageType>() {
            public ELanguageType findValueByNumber(int number) {
              return ELanguageType.forNumber(number);
            }
          };

    private final int value;

    private ELanguageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.ELanguageType)
  }

  /**
   * Protobuf enum {@code css.enum.CrewType}
   */
  public enum CrewType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OWNER = 0;</code>
     */
    OWNER(0),
    /**
     * <code>ADMIN = 1;</code>
     */
    ADMIN(1),
    /**
     * <code>MEMBER = 2;</code>
     */
    MEMBER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OWNER = 0;</code>
     */
    public static final int OWNER_VALUE = 0;
    /**
     * <code>ADMIN = 1;</code>
     */
    public static final int ADMIN_VALUE = 1;
    /**
     * <code>MEMBER = 2;</code>
     */
    public static final int MEMBER_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CrewType valueOf(int value) {
      return forNumber(value);
    }

    public static CrewType forNumber(int value) {
      switch (value) {
        case 0: return OWNER;
        case 1: return ADMIN;
        case 2: return MEMBER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CrewType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CrewType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CrewType>() {
            public CrewType findValueByNumber(int number) {
              return CrewType.forNumber(number);
            }
          };

    private final int value;

    private CrewType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.CrewType)
  }

  /**
   * <pre>
   * 呼叫消息类型
   * </pre>
   *
   * Protobuf enum {@code css.enum.ECallMsgType}
   */
  public enum ECallMsgType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>INVITE = 0;</code>
     */
    INVITE(0),
    /**
     * <code>CONNECT = 1;</code>
     */
    CONNECT(1),
    /**
     * <code>BUSY = 2;</code>
     */
    BUSY(2),
    /**
     * <code>CANCEL = 3;</code>
     */
    CANCEL(3),
    /**
     * <code>REFUSE = 4;</code>
     */
    REFUSE(4),
    /**
     * <code>BYE = 5;</code>
     */
    BYE(5),
    /**
     * <code>REINVITE = 6;</code>
     */
    REINVITE(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INVITE = 0;</code>
     */
    public static final int INVITE_VALUE = 0;
    /**
     * <code>CONNECT = 1;</code>
     */
    public static final int CONNECT_VALUE = 1;
    /**
     * <code>BUSY = 2;</code>
     */
    public static final int BUSY_VALUE = 2;
    /**
     * <code>CANCEL = 3;</code>
     */
    public static final int CANCEL_VALUE = 3;
    /**
     * <code>REFUSE = 4;</code>
     */
    public static final int REFUSE_VALUE = 4;
    /**
     * <code>BYE = 5;</code>
     */
    public static final int BYE_VALUE = 5;
    /**
     * <code>REINVITE = 6;</code>
     */
    public static final int REINVITE_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ECallMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static ECallMsgType forNumber(int value) {
      switch (value) {
        case 0: return INVITE;
        case 1: return CONNECT;
        case 2: return BUSY;
        case 3: return CANCEL;
        case 4: return REFUSE;
        case 5: return BYE;
        case 6: return REINVITE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ECallMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ECallMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ECallMsgType>() {
            public ECallMsgType findValueByNumber(int number) {
              return ECallMsgType.forNumber(number);
            }
          };

    private final int value;

    private ECallMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.ECallMsgType)
  }

  /**
   * <pre>
   * 群类型
   * </pre>
   *
   * Protobuf enum {@code css.enum.EGroupType}
   */
  public enum EGroupType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     *普通群聊
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    NORMAL(0),
    /**
     * <pre>
     *亲情网群聊
     * </pre>
     *
     * <code>FAMILY_NETWORK = 1;</code>
     */
    FAMILY_NETWORK(1),
    /**
     * <pre>
     *和家群组群聊
     * </pre>
     *
     * <code>AND_FAMILY_GROUP = 2;</code>
     */
    AND_FAMILY_GROUP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *普通群聊
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    public static final int NORMAL_VALUE = 0;
    /**
     * <pre>
     *亲情网群聊
     * </pre>
     *
     * <code>FAMILY_NETWORK = 1;</code>
     */
    public static final int FAMILY_NETWORK_VALUE = 1;
    /**
     * <pre>
     *和家群组群聊
     * </pre>
     *
     * <code>AND_FAMILY_GROUP = 2;</code>
     */
    public static final int AND_FAMILY_GROUP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EGroupType valueOf(int value) {
      return forNumber(value);
    }

    public static EGroupType forNumber(int value) {
      switch (value) {
        case 0: return NORMAL;
        case 1: return FAMILY_NETWORK;
        case 2: return AND_FAMILY_GROUP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EGroupType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EGroupType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EGroupType>() {
            public EGroupType findValueByNumber(int number) {
              return EGroupType.forNumber(number);
            }
          };

    private final int value;

    private EGroupType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.EGroupType)
  }

  /**
   * <pre>
   * 内容类型
   * </pre>
   *
   * Protobuf enum {@code css.enum.ContentType}
   */
  public enum ContentType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0),
    /**
     * <code>PIC = 1;</code>
     */
    PIC(1),
    /**
     * <code>AUDIO = 2;</code>
     */
    AUDIO(2),
    /**
     * <code>VIDEO = 3;</code>
     */
    VIDEO(3),
    /**
     * <code>FILE = 4;</code>
     */
    FILE(4),
    /**
     * <code>URL = 5;</code>
     */
    URL(5),
    /**
     * <code>TEXT = 6;</code>
     */
    TEXT(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>PIC = 1;</code>
     */
    public static final int PIC_VALUE = 1;
    /**
     * <code>AUDIO = 2;</code>
     */
    public static final int AUDIO_VALUE = 2;
    /**
     * <code>VIDEO = 3;</code>
     */
    public static final int VIDEO_VALUE = 3;
    /**
     * <code>FILE = 4;</code>
     */
    public static final int FILE_VALUE = 4;
    /**
     * <code>URL = 5;</code>
     */
    public static final int URL_VALUE = 5;
    /**
     * <code>TEXT = 6;</code>
     */
    public static final int TEXT_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentType valueOf(int value) {
      return forNumber(value);
    }

    public static ContentType forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return PIC;
        case 2: return AUDIO;
        case 3: return VIDEO;
        case 4: return FILE;
        case 5: return URL;
        case 6: return TEXT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ContentType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ContentType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ContentType>() {
            public ContentType findValueByNumber(int number) {
              return ContentType.forNumber(number);
            }
          };

    private final int value;

    private ContentType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.enum.ContentType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
