// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: css/ntf.proto

package com.fingo.littlec.proto.css;

public final class Ntf {
  private Ntf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   * 通知类型
   * </pre>
   *
   * Protobuf enum {@code css.ntf.ENtfType}
   */
  public enum ENtfType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * Session相关通知消息
     * </pre>
     *
     * <code>LOGIN_RESPONSE = 0;</code>
     */
    LOGIN_RESPONSE(0),
    /**
     * <pre>
     * 登陆响应
     * </pre>
     *
     * <code>LOGOUT_RESPONSE = 1;</code>
     */
    LOGOUT_RESPONSE(1),
    /**
     * <pre>
     * 踢出通知
     * </pre>
     *
     * <code>KICK_NOTIFICATION = 2;</code>
     */
    KICK_NOTIFICATION(2),
    /**
     * <pre>
     * stream流初始化回复
     * </pre>
     *
     * <code>STREAM_INIT_RESPONSE = 3;</code>
     */
    STREAM_INIT_RESPONSE(3),
    /**
     * <pre>
     * Ping包响应
     * </pre>
     *
     * <code>PING_RESPONSE = 4;</code>
     */
    PING_RESPONSE(4),
    /**
     * <pre>
     * 其他业务通知消息
     * </pre>
     *
     * <code>NEW_MSG = 10;</code>
     */
    NEW_MSG(10),
    /**
     * <pre>
     * 好友变更通知
     * </pre>
     *
     * <code>FRIEND_UPDATE_NOTIFICATION = 11;</code>
     */
    FRIEND_UPDATE_NOTIFICATION(11),
    /**
     * <pre>
     * 消息撤回通知
     * </pre>
     *
     * <code>RETRACT_NOTIFICATION = 12;</code>
     */
    RETRACT_NOTIFICATION(12),
    /**
     * <pre>
     * 伙伴终端消息通知
     * </pre>
     *
     * <code>CARBON_MSG = 13;</code>
     */
    CARBON_MSG(13),
    /**
     * <pre>
     * 呼叫通知
     * </pre>
     *
     * <code>CALL_MSG = 14;</code>
     */
    CALL_MSG(14),
    /**
     * <pre>
     * 群列表变更通知
     * </pre>
     *
     * <code>GROUP_LIST_UPDATE_NOTIFICATION = 15;</code>
     */
    GROUP_LIST_UPDATE_NOTIFICATION(15),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Session相关通知消息
     * </pre>
     *
     * <code>LOGIN_RESPONSE = 0;</code>
     */
    public static final int LOGIN_RESPONSE_VALUE = 0;
    /**
     * <pre>
     * 登陆响应
     * </pre>
     *
     * <code>LOGOUT_RESPONSE = 1;</code>
     */
    public static final int LOGOUT_RESPONSE_VALUE = 1;
    /**
     * <pre>
     * 踢出通知
     * </pre>
     *
     * <code>KICK_NOTIFICATION = 2;</code>
     */
    public static final int KICK_NOTIFICATION_VALUE = 2;
    /**
     * <pre>
     * stream流初始化回复
     * </pre>
     *
     * <code>STREAM_INIT_RESPONSE = 3;</code>
     */
    public static final int STREAM_INIT_RESPONSE_VALUE = 3;
    /**
     * <pre>
     * Ping包响应
     * </pre>
     *
     * <code>PING_RESPONSE = 4;</code>
     */
    public static final int PING_RESPONSE_VALUE = 4;
    /**
     * <pre>
     * 其他业务通知消息
     * </pre>
     *
     * <code>NEW_MSG = 10;</code>
     */
    public static final int NEW_MSG_VALUE = 10;
    /**
     * <pre>
     * 好友变更通知
     * </pre>
     *
     * <code>FRIEND_UPDATE_NOTIFICATION = 11;</code>
     */
    public static final int FRIEND_UPDATE_NOTIFICATION_VALUE = 11;
    /**
     * <pre>
     * 消息撤回通知
     * </pre>
     *
     * <code>RETRACT_NOTIFICATION = 12;</code>
     */
    public static final int RETRACT_NOTIFICATION_VALUE = 12;
    /**
     * <pre>
     * 伙伴终端消息通知
     * </pre>
     *
     * <code>CARBON_MSG = 13;</code>
     */
    public static final int CARBON_MSG_VALUE = 13;
    /**
     * <pre>
     * 呼叫通知
     * </pre>
     *
     * <code>CALL_MSG = 14;</code>
     */
    public static final int CALL_MSG_VALUE = 14;
    /**
     * <pre>
     * 群列表变更通知
     * </pre>
     *
     * <code>GROUP_LIST_UPDATE_NOTIFICATION = 15;</code>
     */
    public static final int GROUP_LIST_UPDATE_NOTIFICATION_VALUE = 15;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ENtfType valueOf(int value) {
      return forNumber(value);
    }

    public static ENtfType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN_RESPONSE;
        case 1: return LOGOUT_RESPONSE;
        case 2: return KICK_NOTIFICATION;
        case 3: return STREAM_INIT_RESPONSE;
        case 4: return PING_RESPONSE;
        case 10: return NEW_MSG;
        case 11: return FRIEND_UPDATE_NOTIFICATION;
        case 12: return RETRACT_NOTIFICATION;
        case 13: return CARBON_MSG;
        case 14: return CALL_MSG;
        case 15: return GROUP_LIST_UPDATE_NOTIFICATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ENtfType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ENtfType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ENtfType>() {
            public ENtfType findValueByNumber(int number) {
              return ENtfType.forNumber(number);
            }
          };

    private final int value;

    private ENtfType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:css.ntf.ENtfType)
  }

  public interface NewMsgNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.ntf.NewMsgNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   * 新消息通知
   * </pre>
   *
   * Protobuf type {@code css.ntf.NewMsgNotification}
   */
  public  static final class NewMsgNotification extends
      com.google.protobuf.GeneratedMessageLite<
          NewMsgNotification, NewMsgNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:css.ntf.NewMsgNotification)
      NewMsgNotificationOrBuilder {
    private NewMsgNotification() {
      content_ = "";
    }
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.String content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      content_ = value;
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void clearContent() {

      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      content_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeString(1, getContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getContent());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Ntf.NewMsgNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 新消息通知
     * </pre>
     *
     * Protobuf type {@code css.ntf.NewMsgNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NewMsgNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.ntf.NewMsgNotification)
        com.fingo.littlec.proto.css.Ntf.NewMsgNotificationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Ntf.NewMsgNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string content = 1;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.ntf.NewMsgNotification)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Ntf.NewMsgNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Ntf.NewMsgNotification other = (com.fingo.littlec.proto.css.Ntf.NewMsgNotification) arg1;
          content_ = visitor.visitString(!content_.isEmpty(), content_,
              !other.content_.isEmpty(), other.content_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  content_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Ntf.NewMsgNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.ntf.NewMsgNotification)
    private static final com.fingo.littlec.proto.css.Ntf.NewMsgNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NewMsgNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Ntf.NewMsgNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NewMsgNotification> PARSER;

    public static com.google.protobuf.Parser<NewMsgNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CarbonMsgNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.ntf.CarbonMsgNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional string appkey = 2;</code>
     */
    java.lang.String getAppkey();
    /**
     * <code>optional string appkey = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <code>optional string sender_username = 3;</code>
     */
    java.lang.String getSenderUsername();
    /**
     * <code>optional string sender_username = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderUsernameBytes();

    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    int getSenderClientTypeValue();
    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    com.fingo.littlec.proto.css.Enum.EClientType getSenderClientType();
  }
  /**
   * <pre>
   * 伙伴终端消息通知
   * </pre>
   *
   * Protobuf type {@code css.ntf.CarbonMsgNotification}
   */
  public  static final class CarbonMsgNotification extends
      com.google.protobuf.GeneratedMessageLite<
          CarbonMsgNotification, CarbonMsgNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:css.ntf.CarbonMsgNotification)
      CarbonMsgNotificationOrBuilder {
    private CarbonMsgNotification() {
      content_ = "";
      appkey_ = "";
      senderUsername_ = "";
    }
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.String content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      content_ = value;
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void clearContent() {

      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      content_ = value.toStringUtf8();
    }

    public static final int APPKEY_FIELD_NUMBER = 2;
    private java.lang.String appkey_;
    /**
     * <code>optional string appkey = 2;</code>
     */
    public java.lang.String getAppkey() {
      return appkey_;
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appkey_);
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    private void setAppkey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      appkey_ = value;
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    private void clearAppkey() {

      appkey_ = getDefaultInstance().getAppkey();
    }
    /**
     * <code>optional string appkey = 2;</code>
     */
    private void setAppkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      appkey_ = value.toStringUtf8();
    }

    public static final int SENDER_USERNAME_FIELD_NUMBER = 3;
    private java.lang.String senderUsername_;
    /**
     * <code>optional string sender_username = 3;</code>
     */
    public java.lang.String getSenderUsername() {
      return senderUsername_;
    }
    /**
     * <code>optional string sender_username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderUsernameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(senderUsername_);
    }
    /**
     * <code>optional string sender_username = 3;</code>
     */
    private void setSenderUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      senderUsername_ = value;
    }
    /**
     * <code>optional string sender_username = 3;</code>
     */
    private void clearSenderUsername() {

      senderUsername_ = getDefaultInstance().getSenderUsername();
    }
    /**
     * <code>optional string sender_username = 3;</code>
     */
    private void setSenderUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      senderUsername_ = value.toStringUtf8();
    }

    public static final int SENDER_CLIENT_TYPE_FIELD_NUMBER = 4;
    private int senderClientType_;
    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    public int getSenderClientTypeValue() {
      return senderClientType_;
    }
    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    public com.fingo.littlec.proto.css.Enum.EClientType getSenderClientType() {
      com.fingo.littlec.proto.css.Enum.EClientType result = com.fingo.littlec.proto.css.Enum.EClientType.forNumber(senderClientType_);
      return result == null ? com.fingo.littlec.proto.css.Enum.EClientType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    private void setSenderClientTypeValue(int value) {
        senderClientType_ = value;
    }
    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    private void setSenderClientType(com.fingo.littlec.proto.css.Enum.EClientType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      senderClientType_ = value.getNumber();
    }
    /**
     * <pre>
     * 消息发送终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
     */
    private void clearSenderClientType() {

      senderClientType_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeString(1, getContent());
      }
      if (!appkey_.isEmpty()) {
        output.writeString(2, getAppkey());
      }
      if (!senderUsername_.isEmpty()) {
        output.writeString(3, getSenderUsername());
      }
      if (senderClientType_ != com.fingo.littlec.proto.css.Enum.EClientType.UNKNOWN.getNumber()) {
        output.writeEnum(4, senderClientType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getContent());
      }
      if (!appkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getAppkey());
      }
      if (!senderUsername_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSenderUsername());
      }
      if (senderClientType_ != com.fingo.littlec.proto.css.Enum.EClientType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, senderClientType_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 伙伴终端消息通知
     * </pre>
     *
     * Protobuf type {@code css.ntf.CarbonMsgNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CarbonMsgNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.ntf.CarbonMsgNotification)
        com.fingo.littlec.proto.css.Ntf.CarbonMsgNotificationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string content = 1;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <code>optional string appkey = 2;</code>
       */
      public java.lang.String getAppkey() {
        return instance.getAppkey();
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        return instance.getAppkeyBytes();
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public Builder setAppkey(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppkey(value);
        return this;
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public Builder clearAppkey() {
        copyOnWrite();
        instance.clearAppkey();
        return this;
      }
      /**
       * <code>optional string appkey = 2;</code>
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppkeyBytes(value);
        return this;
      }

      /**
       * <code>optional string sender_username = 3;</code>
       */
      public java.lang.String getSenderUsername() {
        return instance.getSenderUsername();
      }
      /**
       * <code>optional string sender_username = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderUsernameBytes() {
        return instance.getSenderUsernameBytes();
      }
      /**
       * <code>optional string sender_username = 3;</code>
       */
      public Builder setSenderUsername(
          java.lang.String value) {
        copyOnWrite();
        instance.setSenderUsername(value);
        return this;
      }
      /**
       * <code>optional string sender_username = 3;</code>
       */
      public Builder clearSenderUsername() {
        copyOnWrite();
        instance.clearSenderUsername();
        return this;
      }
      /**
       * <code>optional string sender_username = 3;</code>
       */
      public Builder setSenderUsernameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderUsernameBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息发送终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
       */
      public int getSenderClientTypeValue() {
        return instance.getSenderClientTypeValue();
      }
      /**
       * <pre>
       * 消息发送终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
       */
      public Builder setSenderClientTypeValue(int value) {
        copyOnWrite();
        instance.setSenderClientTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * 消息发送终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
       */
      public com.fingo.littlec.proto.css.Enum.EClientType getSenderClientType() {
        return instance.getSenderClientType();
      }
      /**
       * <pre>
       * 消息发送终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
       */
      public Builder setSenderClientType(com.fingo.littlec.proto.css.Enum.EClientType value) {
        copyOnWrite();
        instance.setSenderClientType(value);
        return this;
      }
      /**
       * <pre>
       * 消息发送终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType sender_client_type = 4;</code>
       */
      public Builder clearSenderClientType() {
        copyOnWrite();
        instance.clearSenderClientType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.ntf.CarbonMsgNotification)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification other = (com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification) arg1;
          content_ = visitor.visitString(!content_.isEmpty(), content_,
              !other.content_.isEmpty(), other.content_);
          appkey_ = visitor.visitString(!appkey_.isEmpty(), appkey_,
              !other.appkey_.isEmpty(), other.appkey_);
          senderUsername_ = visitor.visitString(!senderUsername_.isEmpty(), senderUsername_,
              !other.senderUsername_.isEmpty(), other.senderUsername_);
          senderClientType_ = visitor.visitInt(senderClientType_ != 0, senderClientType_,    other.senderClientType_ != 0, other.senderClientType_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  content_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  appkey_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  senderUsername_ = s;
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  senderClientType_ = rawValue;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.ntf.CarbonMsgNotification)
    private static final com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CarbonMsgNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Ntf.CarbonMsgNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CarbonMsgNotification> PARSER;

    public static com.google.protobuf.Parser<CarbonMsgNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CallMsgNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.ntf.CallMsgNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    int getCallMsgTypeValue();
    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    com.fingo.littlec.proto.css.Enum.ECallMsgType getCallMsgType();

    /**
     * <code>optional string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   * 呼叫通知
   * </pre>
   *
   * Protobuf type {@code css.ntf.CallMsgNotification}
   */
  public  static final class CallMsgNotification extends
      com.google.protobuf.GeneratedMessageLite<
          CallMsgNotification, CallMsgNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:css.ntf.CallMsgNotification)
      CallMsgNotificationOrBuilder {
    private CallMsgNotification() {
      content_ = "";
    }
    public static final int CALL_MSG_TYPE_FIELD_NUMBER = 1;
    private int callMsgType_;
    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    public int getCallMsgTypeValue() {
      return callMsgType_;
    }
    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    public com.fingo.littlec.proto.css.Enum.ECallMsgType getCallMsgType() {
      com.fingo.littlec.proto.css.Enum.ECallMsgType result = com.fingo.littlec.proto.css.Enum.ECallMsgType.forNumber(callMsgType_);
      return result == null ? com.fingo.littlec.proto.css.Enum.ECallMsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    private void setCallMsgTypeValue(int value) {
        callMsgType_ = value;
    }
    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    private void setCallMsgType(com.fingo.littlec.proto.css.Enum.ECallMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      callMsgType_ = value.getNumber();
    }
    /**
     * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
     */
    private void clearCallMsgType() {

      callMsgType_ = 0;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.String content_;
    /**
     * <code>optional string content = 2;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>optional string content = 2;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      content_ = value;
    }
    /**
     * <code>optional string content = 2;</code>
     */
    private void clearContent() {

      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>optional string content = 2;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      content_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (callMsgType_ != com.fingo.littlec.proto.css.Enum.ECallMsgType.INVITE.getNumber()) {
        output.writeEnum(1, callMsgType_);
      }
      if (!content_.isEmpty()) {
        output.writeString(2, getContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (callMsgType_ != com.fingo.littlec.proto.css.Enum.ECallMsgType.INVITE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, callMsgType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getContent());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Ntf.CallMsgNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 呼叫通知
     * </pre>
     *
     * Protobuf type {@code css.ntf.CallMsgNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CallMsgNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.ntf.CallMsgNotification)
        com.fingo.littlec.proto.css.Ntf.CallMsgNotificationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Ntf.CallMsgNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
       */
      public int getCallMsgTypeValue() {
        return instance.getCallMsgTypeValue();
      }
      /**
       * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
       */
      public Builder setCallMsgTypeValue(int value) {
        copyOnWrite();
        instance.setCallMsgTypeValue(value);
        return this;
      }
      /**
       * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
       */
      public com.fingo.littlec.proto.css.Enum.ECallMsgType getCallMsgType() {
        return instance.getCallMsgType();
      }
      /**
       * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
       */
      public Builder setCallMsgType(com.fingo.littlec.proto.css.Enum.ECallMsgType value) {
        copyOnWrite();
        instance.setCallMsgType(value);
        return this;
      }
      /**
       * <code>optional .css.enum.ECallMsgType call_msg_type = 1;</code>
       */
      public Builder clearCallMsgType() {
        copyOnWrite();
        instance.clearCallMsgType();
        return this;
      }

      /**
       * <code>optional string content = 2;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.ntf.CallMsgNotification)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Ntf.CallMsgNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Ntf.CallMsgNotification other = (com.fingo.littlec.proto.css.Ntf.CallMsgNotification) arg1;
          callMsgType_ = visitor.visitInt(callMsgType_ != 0, callMsgType_,    other.callMsgType_ != 0, other.callMsgType_);
          content_ = visitor.visitString(!content_.isEmpty(), content_,
              !other.content_.isEmpty(), other.content_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  callMsgType_ = rawValue;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  content_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Ntf.CallMsgNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.ntf.CallMsgNotification)
    private static final com.fingo.littlec.proto.css.Ntf.CallMsgNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallMsgNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Ntf.CallMsgNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CallMsgNotification> PARSER;

    public static com.google.protobuf.Parser<CallMsgNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface KickNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.ntf.KickNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    int getLoginClientTypeValue();
    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    com.fingo.littlec.proto.css.Enum.EClientType getLoginClientType();
  }
  /**
   * <pre>
   * 踢出通知
   * </pre>
   *
   * Protobuf type {@code css.ntf.KickNotification}
   */
  public  static final class KickNotification extends
      com.google.protobuf.GeneratedMessageLite<
          KickNotification, KickNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:css.ntf.KickNotification)
      KickNotificationOrBuilder {
    private KickNotification() {
    }
    public static final int LOGIN_CLIENT_TYPE_FIELD_NUMBER = 1;
    private int loginClientType_;
    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    public int getLoginClientTypeValue() {
      return loginClientType_;
    }
    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    public com.fingo.littlec.proto.css.Enum.EClientType getLoginClientType() {
      com.fingo.littlec.proto.css.Enum.EClientType result = com.fingo.littlec.proto.css.Enum.EClientType.forNumber(loginClientType_);
      return result == null ? com.fingo.littlec.proto.css.Enum.EClientType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    private void setLoginClientTypeValue(int value) {
        loginClientType_ = value;
    }
    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    private void setLoginClientType(com.fingo.littlec.proto.css.Enum.EClientType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      loginClientType_ = value.getNumber();
    }
    /**
     * <pre>
     * 新登录终端类型
     * </pre>
     *
     * <code>optional .css.enum.EClientType login_client_type = 1;</code>
     */
    private void clearLoginClientType() {

      loginClientType_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (loginClientType_ != com.fingo.littlec.proto.css.Enum.EClientType.UNKNOWN.getNumber()) {
        output.writeEnum(1, loginClientType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (loginClientType_ != com.fingo.littlec.proto.css.Enum.EClientType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, loginClientType_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.KickNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Ntf.KickNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 踢出通知
     * </pre>
     *
     * Protobuf type {@code css.ntf.KickNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          KickNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.ntf.KickNotification)
        com.fingo.littlec.proto.css.Ntf.KickNotificationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Ntf.KickNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 新登录终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType login_client_type = 1;</code>
       */
      public int getLoginClientTypeValue() {
        return instance.getLoginClientTypeValue();
      }
      /**
       * <pre>
       * 新登录终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType login_client_type = 1;</code>
       */
      public Builder setLoginClientTypeValue(int value) {
        copyOnWrite();
        instance.setLoginClientTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * 新登录终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType login_client_type = 1;</code>
       */
      public com.fingo.littlec.proto.css.Enum.EClientType getLoginClientType() {
        return instance.getLoginClientType();
      }
      /**
       * <pre>
       * 新登录终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType login_client_type = 1;</code>
       */
      public Builder setLoginClientType(com.fingo.littlec.proto.css.Enum.EClientType value) {
        copyOnWrite();
        instance.setLoginClientType(value);
        return this;
      }
      /**
       * <pre>
       * 新登录终端类型
       * </pre>
       *
       * <code>optional .css.enum.EClientType login_client_type = 1;</code>
       */
      public Builder clearLoginClientType() {
        copyOnWrite();
        instance.clearLoginClientType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.ntf.KickNotification)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Ntf.KickNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Ntf.KickNotification other = (com.fingo.littlec.proto.css.Ntf.KickNotification) arg1;
          loginClientType_ = visitor.visitInt(loginClientType_ != 0, loginClientType_,    other.loginClientType_ != 0, other.loginClientType_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  loginClientType_ = rawValue;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Ntf.KickNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.ntf.KickNotification)
    private static final com.fingo.littlec.proto.css.Ntf.KickNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KickNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Ntf.KickNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<KickNotification> PARSER;

    public static com.google.protobuf.Parser<KickNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FriendUpdateNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.ntf.FriendUpdateNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   * 好友变更通知
   * </pre>
   *
   * Protobuf type {@code css.ntf.FriendUpdateNotification}
   */
  public  static final class FriendUpdateNotification extends
      com.google.protobuf.GeneratedMessageLite<
          FriendUpdateNotification, FriendUpdateNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:css.ntf.FriendUpdateNotification)
      FriendUpdateNotificationOrBuilder {
    private FriendUpdateNotification() {
      content_ = "";
    }
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.String content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      content_ = value;
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void clearContent() {

      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>optional string content = 1;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      content_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeString(1, getContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getContent());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 好友变更通知
     * </pre>
     *
     * Protobuf type {@code css.ntf.FriendUpdateNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FriendUpdateNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.ntf.FriendUpdateNotification)
        com.fingo.littlec.proto.css.Ntf.FriendUpdateNotificationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string content = 1;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.ntf.FriendUpdateNotification)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification other = (com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification) arg1;
          content_ = visitor.visitString(!content_.isEmpty(), content_,
              !other.content_.isEmpty(), other.content_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  content_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.ntf.FriendUpdateNotification)
    private static final com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FriendUpdateNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Ntf.FriendUpdateNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FriendUpdateNotification> PARSER;

    public static com.google.protobuf.Parser<FriendUpdateNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RetractNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:css.ntf.RetractNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string appkey = 1;</code>
     */
    java.lang.String getAppkey();
    /**
     * <code>optional string appkey = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    int getMsgTypeValue();
    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    com.fingo.littlec.proto.css.Msg.EMsgType getMsgType();

    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    java.lang.String getFromUsername();
    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromUsernameBytes();

    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    java.lang.String getUri();
    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <pre>
     * 被撤回消息guid
     * </pre>
     *
     * <code>optional uint64 retract_guid = 5;</code>
     */
    long getRetractGuid();
  }
  /**
   * <pre>
   * 消息撤回通知
   * </pre>
   *
   * Protobuf type {@code css.ntf.RetractNotification}
   */
  public  static final class RetractNotification extends
      com.google.protobuf.GeneratedMessageLite<
          RetractNotification, RetractNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:css.ntf.RetractNotification)
      RetractNotificationOrBuilder {
    private RetractNotification() {
      appkey_ = "";
      fromUsername_ = "";
      uri_ = "";
    }
    public static final int APPKEY_FIELD_NUMBER = 1;
    private java.lang.String appkey_;
    /**
     * <code>optional string appkey = 1;</code>
     */
    public java.lang.String getAppkey() {
      return appkey_;
    }
    /**
     * <code>optional string appkey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appkey_);
    }
    /**
     * <code>optional string appkey = 1;</code>
     */
    private void setAppkey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      appkey_ = value;
    }
    /**
     * <code>optional string appkey = 1;</code>
     */
    private void clearAppkey() {

      appkey_ = getDefaultInstance().getAppkey();
    }
    /**
     * <code>optional string appkey = 1;</code>
     */
    private void setAppkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      appkey_ = value.toStringUtf8();
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    public com.fingo.littlec.proto.css.Msg.EMsgType getMsgType() {
      com.fingo.littlec.proto.css.Msg.EMsgType result = com.fingo.littlec.proto.css.Msg.EMsgType.forNumber(msgType_);
      return result == null ? com.fingo.littlec.proto.css.Msg.EMsgType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    private void setMsgTypeValue(int value) {
        msgType_ = value;
    }
    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    private void setMsgType(com.fingo.littlec.proto.css.Msg.EMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      msgType_ = value.getNumber();
    }
    /**
     * <pre>
     * 单聊 or群聊
     * </pre>
     *
     * <code>optional .css.msg.EMsgType msg_type = 2;</code>
     */
    private void clearMsgType() {

      msgType_ = 0;
    }

    public static final int FROM_USERNAME_FIELD_NUMBER = 3;
    private java.lang.String fromUsername_;
    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    public java.lang.String getFromUsername() {
      return fromUsername_;
    }
    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromUsernameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fromUsername_);
    }
    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    private void setFromUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      fromUsername_ = value;
    }
    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    private void clearFromUsername() {

      fromUsername_ = getDefaultInstance().getFromUsername();
    }
    /**
     * <pre>
     * 撤回者
     * </pre>
     *
     * <code>optional string from_username = 3;</code>
     */
    private void setFromUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      fromUsername_ = value.toStringUtf8();
    }

    public static final int URI_FIELD_NUMBER = 4;
    private java.lang.String uri_;
    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public java.lang.String getUri() {
      return uri_;
    }
    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(uri_);
    }
    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    private void setUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      uri_ = value;
    }
    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    private void clearUri() {

      uri_ = getDefaultInstance().getUri();
    }
    /**
     * <pre>
     * 群聊uri
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    private void setUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      uri_ = value.toStringUtf8();
    }

    public static final int RETRACT_GUID_FIELD_NUMBER = 5;
    private long retractGuid_;
    /**
     * <pre>
     * 被撤回消息guid
     * </pre>
     *
     * <code>optional uint64 retract_guid = 5;</code>
     */
    public long getRetractGuid() {
      return retractGuid_;
    }
    /**
     * <pre>
     * 被撤回消息guid
     * </pre>
     *
     * <code>optional uint64 retract_guid = 5;</code>
     */
    private void setRetractGuid(long value) {

      retractGuid_ = value;
    }
    /**
     * <pre>
     * 被撤回消息guid
     * </pre>
     *
     * <code>optional uint64 retract_guid = 5;</code>
     */
    private void clearRetractGuid() {

      retractGuid_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!appkey_.isEmpty()) {
        output.writeString(1, getAppkey());
      }
      if (msgType_ != com.fingo.littlec.proto.css.Msg.EMsgType.CHAT_MSG.getNumber()) {
        output.writeEnum(2, msgType_);
      }
      if (!fromUsername_.isEmpty()) {
        output.writeString(3, getFromUsername());
      }
      if (!uri_.isEmpty()) {
        output.writeString(4, getUri());
      }
      if (retractGuid_ != 0L) {
        output.writeUInt64(5, retractGuid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!appkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAppkey());
      }
      if (msgType_ != com.fingo.littlec.proto.css.Msg.EMsgType.CHAT_MSG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgType_);
      }
      if (!fromUsername_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getFromUsername());
      }
      if (!uri_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getUri());
      }
      if (retractGuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, retractGuid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fingo.littlec.proto.css.Ntf.RetractNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fingo.littlec.proto.css.Ntf.RetractNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 消息撤回通知
     * </pre>
     *
     * Protobuf type {@code css.ntf.RetractNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RetractNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:css.ntf.RetractNotification)
        com.fingo.littlec.proto.css.Ntf.RetractNotificationOrBuilder {
      // Construct using com.fingo.littlec.proto.css.Ntf.RetractNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string appkey = 1;</code>
       */
      public java.lang.String getAppkey() {
        return instance.getAppkey();
      }
      /**
       * <code>optional string appkey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        return instance.getAppkeyBytes();
      }
      /**
       * <code>optional string appkey = 1;</code>
       */
      public Builder setAppkey(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppkey(value);
        return this;
      }
      /**
       * <code>optional string appkey = 1;</code>
       */
      public Builder clearAppkey() {
        copyOnWrite();
        instance.clearAppkey();
        return this;
      }
      /**
       * <code>optional string appkey = 1;</code>
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppkeyBytes(value);
        return this;
      }

      /**
       * <pre>
       * 单聊 or群聊
       * </pre>
       *
       * <code>optional .css.msg.EMsgType msg_type = 2;</code>
       */
      public int getMsgTypeValue() {
        return instance.getMsgTypeValue();
      }
      /**
       * <pre>
       * 单聊 or群聊
       * </pre>
       *
       * <code>optional .css.msg.EMsgType msg_type = 2;</code>
       */
      public Builder setMsgTypeValue(int value) {
        copyOnWrite();
        instance.setMsgTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * 单聊 or群聊
       * </pre>
       *
       * <code>optional .css.msg.EMsgType msg_type = 2;</code>
       */
      public com.fingo.littlec.proto.css.Msg.EMsgType getMsgType() {
        return instance.getMsgType();
      }
      /**
       * <pre>
       * 单聊 or群聊
       * </pre>
       *
       * <code>optional .css.msg.EMsgType msg_type = 2;</code>
       */
      public Builder setMsgType(com.fingo.littlec.proto.css.Msg.EMsgType value) {
        copyOnWrite();
        instance.setMsgType(value);
        return this;
      }
      /**
       * <pre>
       * 单聊 or群聊
       * </pre>
       *
       * <code>optional .css.msg.EMsgType msg_type = 2;</code>
       */
      public Builder clearMsgType() {
        copyOnWrite();
        instance.clearMsgType();
        return this;
      }

      /**
       * <pre>
       * 撤回者
       * </pre>
       *
       * <code>optional string from_username = 3;</code>
       */
      public java.lang.String getFromUsername() {
        return instance.getFromUsername();
      }
      /**
       * <pre>
       * 撤回者
       * </pre>
       *
       * <code>optional string from_username = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromUsernameBytes() {
        return instance.getFromUsernameBytes();
      }
      /**
       * <pre>
       * 撤回者
       * </pre>
       *
       * <code>optional string from_username = 3;</code>
       */
      public Builder setFromUsername(
          java.lang.String value) {
        copyOnWrite();
        instance.setFromUsername(value);
        return this;
      }
      /**
       * <pre>
       * 撤回者
       * </pre>
       *
       * <code>optional string from_username = 3;</code>
       */
      public Builder clearFromUsername() {
        copyOnWrite();
        instance.clearFromUsername();
        return this;
      }
      /**
       * <pre>
       * 撤回者
       * </pre>
       *
       * <code>optional string from_username = 3;</code>
       */
      public Builder setFromUsernameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFromUsernameBytes(value);
        return this;
      }

      /**
       * <pre>
       * 群聊uri
       * </pre>
       *
       * <code>optional string uri = 4;</code>
       */
      public java.lang.String getUri() {
        return instance.getUri();
      }
      /**
       * <pre>
       * 群聊uri
       * </pre>
       *
       * <code>optional string uri = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        return instance.getUriBytes();
      }
      /**
       * <pre>
       * 群聊uri
       * </pre>
       *
       * <code>optional string uri = 4;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        copyOnWrite();
        instance.setUri(value);
        return this;
      }
      /**
       * <pre>
       * 群聊uri
       * </pre>
       *
       * <code>optional string uri = 4;</code>
       */
      public Builder clearUri() {
        copyOnWrite();
        instance.clearUri();
        return this;
      }
      /**
       * <pre>
       * 群聊uri
       * </pre>
       *
       * <code>optional string uri = 4;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUriBytes(value);
        return this;
      }

      /**
       * <pre>
       * 被撤回消息guid
       * </pre>
       *
       * <code>optional uint64 retract_guid = 5;</code>
       */
      public long getRetractGuid() {
        return instance.getRetractGuid();
      }
      /**
       * <pre>
       * 被撤回消息guid
       * </pre>
       *
       * <code>optional uint64 retract_guid = 5;</code>
       */
      public Builder setRetractGuid(long value) {
        copyOnWrite();
        instance.setRetractGuid(value);
        return this;
      }
      /**
       * <pre>
       * 被撤回消息guid
       * </pre>
       *
       * <code>optional uint64 retract_guid = 5;</code>
       */
      public Builder clearRetractGuid() {
        copyOnWrite();
        instance.clearRetractGuid();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:css.ntf.RetractNotification)
    }
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fingo.littlec.proto.css.Ntf.RetractNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fingo.littlec.proto.css.Ntf.RetractNotification other = (com.fingo.littlec.proto.css.Ntf.RetractNotification) arg1;
          appkey_ = visitor.visitString(!appkey_.isEmpty(), appkey_,
              !other.appkey_.isEmpty(), other.appkey_);
          msgType_ = visitor.visitInt(msgType_ != 0, msgType_,    other.msgType_ != 0, other.msgType_);
          fromUsername_ = visitor.visitString(!fromUsername_.isEmpty(), fromUsername_,
              !other.fromUsername_.isEmpty(), other.fromUsername_);
          uri_ = visitor.visitString(!uri_.isEmpty(), uri_,
              !other.uri_.isEmpty(), other.uri_);
          retractGuid_ = visitor.visitLong(retractGuid_ != 0L, retractGuid_,
              other.retractGuid_ != 0L, other.retractGuid_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  appkey_ = s;
                  break;
                }
                case 16: {
                  int rawValue = input.readEnum();

                  msgType_ = rawValue;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  fromUsername_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  uri_ = s;
                  break;
                }
                case 40: {

                  retractGuid_ = input.readUInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fingo.littlec.proto.css.Ntf.RetractNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:css.ntf.RetractNotification)
    private static final com.fingo.littlec.proto.css.Ntf.RetractNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RetractNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fingo.littlec.proto.css.Ntf.RetractNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RetractNotification> PARSER;

    public static com.google.protobuf.Parser<RetractNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
