// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: css/grpc.proto

package com.fingo.littlec.connector.service.css;

public final class Grpc {
  private Grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
