package com.littlec.sdk.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.littlec.sdk.database.entity.MemberEntity;
import com.littlec.sdk.database.entity.MediaEntity;
import com.littlec.sdk.database.entity.FriendReqDBEntity;
import com.littlec.sdk.database.entity.ContactEntity;
import com.littlec.sdk.database.entity.UploadDBEntity;
import com.littlec.sdk.database.entity.TagEntity;
import com.littlec.sdk.database.entity.ExcTaskDBEntity;
import com.littlec.sdk.database.entity.GroupEntity;
import com.littlec.sdk.database.entity.MessageEntity;
import com.littlec.sdk.database.entity.DownloadDBEntity;
import com.littlec.sdk.database.entity.ConversationEntity;

import com.littlec.sdk.database.dao.MemberEntityDao;
import com.littlec.sdk.database.dao.MediaEntityDao;
import com.littlec.sdk.database.dao.FriendReqDBEntityDao;
import com.littlec.sdk.database.dao.ContactEntityDao;
import com.littlec.sdk.database.dao.UploadDBEntityDao;
import com.littlec.sdk.database.dao.TagEntityDao;
import com.littlec.sdk.database.dao.ExcTaskDBEntityDao;
import com.littlec.sdk.database.dao.GroupEntityDao;
import com.littlec.sdk.database.dao.MessageEntityDao;
import com.littlec.sdk.database.dao.DownloadDBEntityDao;
import com.littlec.sdk.database.dao.ConversationEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memberEntityDaoConfig;
    private final DaoConfig mediaEntityDaoConfig;
    private final DaoConfig friendReqDBEntityDaoConfig;
    private final DaoConfig contactEntityDaoConfig;
    private final DaoConfig uploadDBEntityDaoConfig;
    private final DaoConfig tagEntityDaoConfig;
    private final DaoConfig excTaskDBEntityDaoConfig;
    private final DaoConfig groupEntityDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig downloadDBEntityDaoConfig;
    private final DaoConfig conversationEntityDaoConfig;

    private final MemberEntityDao memberEntityDao;
    private final MediaEntityDao mediaEntityDao;
    private final FriendReqDBEntityDao friendReqDBEntityDao;
    private final ContactEntityDao contactEntityDao;
    private final UploadDBEntityDao uploadDBEntityDao;
    private final TagEntityDao tagEntityDao;
    private final ExcTaskDBEntityDao excTaskDBEntityDao;
    private final GroupEntityDao groupEntityDao;
    private final MessageEntityDao messageEntityDao;
    private final DownloadDBEntityDao downloadDBEntityDao;
    private final ConversationEntityDao conversationEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memberEntityDaoConfig = daoConfigMap.get(MemberEntityDao.class).clone();
        memberEntityDaoConfig.initIdentityScope(type);

        mediaEntityDaoConfig = daoConfigMap.get(MediaEntityDao.class).clone();
        mediaEntityDaoConfig.initIdentityScope(type);

        friendReqDBEntityDaoConfig = daoConfigMap.get(FriendReqDBEntityDao.class).clone();
        friendReqDBEntityDaoConfig.initIdentityScope(type);

        contactEntityDaoConfig = daoConfigMap.get(ContactEntityDao.class).clone();
        contactEntityDaoConfig.initIdentityScope(type);

        uploadDBEntityDaoConfig = daoConfigMap.get(UploadDBEntityDao.class).clone();
        uploadDBEntityDaoConfig.initIdentityScope(type);

        tagEntityDaoConfig = daoConfigMap.get(TagEntityDao.class).clone();
        tagEntityDaoConfig.initIdentityScope(type);

        excTaskDBEntityDaoConfig = daoConfigMap.get(ExcTaskDBEntityDao.class).clone();
        excTaskDBEntityDaoConfig.initIdentityScope(type);

        groupEntityDaoConfig = daoConfigMap.get(GroupEntityDao.class).clone();
        groupEntityDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        downloadDBEntityDaoConfig = daoConfigMap.get(DownloadDBEntityDao.class).clone();
        downloadDBEntityDaoConfig.initIdentityScope(type);

        conversationEntityDaoConfig = daoConfigMap.get(ConversationEntityDao.class).clone();
        conversationEntityDaoConfig.initIdentityScope(type);

        memberEntityDao = new MemberEntityDao(memberEntityDaoConfig, this);
        mediaEntityDao = new MediaEntityDao(mediaEntityDaoConfig, this);
        friendReqDBEntityDao = new FriendReqDBEntityDao(friendReqDBEntityDaoConfig, this);
        contactEntityDao = new ContactEntityDao(contactEntityDaoConfig, this);
        uploadDBEntityDao = new UploadDBEntityDao(uploadDBEntityDaoConfig, this);
        tagEntityDao = new TagEntityDao(tagEntityDaoConfig, this);
        excTaskDBEntityDao = new ExcTaskDBEntityDao(excTaskDBEntityDaoConfig, this);
        groupEntityDao = new GroupEntityDao(groupEntityDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        downloadDBEntityDao = new DownloadDBEntityDao(downloadDBEntityDaoConfig, this);
        conversationEntityDao = new ConversationEntityDao(conversationEntityDaoConfig, this);

        registerDao(MemberEntity.class, memberEntityDao);
        registerDao(MediaEntity.class, mediaEntityDao);
        registerDao(FriendReqDBEntity.class, friendReqDBEntityDao);
        registerDao(ContactEntity.class, contactEntityDao);
        registerDao(UploadDBEntity.class, uploadDBEntityDao);
        registerDao(TagEntity.class, tagEntityDao);
        registerDao(ExcTaskDBEntity.class, excTaskDBEntityDao);
        registerDao(GroupEntity.class, groupEntityDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(DownloadDBEntity.class, downloadDBEntityDao);
        registerDao(ConversationEntity.class, conversationEntityDao);
    }
    
    public void clear() {
        memberEntityDaoConfig.clearIdentityScope();
        mediaEntityDaoConfig.clearIdentityScope();
        friendReqDBEntityDaoConfig.clearIdentityScope();
        contactEntityDaoConfig.clearIdentityScope();
        uploadDBEntityDaoConfig.clearIdentityScope();
        tagEntityDaoConfig.clearIdentityScope();
        excTaskDBEntityDaoConfig.clearIdentityScope();
        groupEntityDaoConfig.clearIdentityScope();
        messageEntityDaoConfig.clearIdentityScope();
        downloadDBEntityDaoConfig.clearIdentityScope();
        conversationEntityDaoConfig.clearIdentityScope();
    }

    public MemberEntityDao getMemberEntityDao() {
        return memberEntityDao;
    }

    public MediaEntityDao getMediaEntityDao() {
        return mediaEntityDao;
    }

    public FriendReqDBEntityDao getFriendReqDBEntityDao() {
        return friendReqDBEntityDao;
    }

    public ContactEntityDao getContactEntityDao() {
        return contactEntityDao;
    }

    public UploadDBEntityDao getUploadDBEntityDao() {
        return uploadDBEntityDao;
    }

    public TagEntityDao getTagEntityDao() {
        return tagEntityDao;
    }

    public ExcTaskDBEntityDao getExcTaskDBEntityDao() {
        return excTaskDBEntityDao;
    }

    public GroupEntityDao getGroupEntityDao() {
        return groupEntityDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public DownloadDBEntityDao getDownloadDBEntityDao() {
        return downloadDBEntityDao;
    }

    public ConversationEntityDao getConversationEntityDao() {
        return conversationEntityDao;
    }

}
