package com.littlec.sdk.database.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "Contact".
 */
@Entity
public class ContactEntity  implements Parcelable{
    @Id
    private String userName;
    private String nickName;
    private int mute;
    private String phone;
    private String display;
    private String thumbnail_link;
    private String original_link;
    private String data1;
    @Generated(hash = 1266998304)
    public ContactEntity(String userName, String nickName, int mute, String phone,
            String display, String thumbnail_link, String original_link,
            String data1) {
        this.userName = userName;
        this.nickName = nickName;
        this.mute = mute;
        this.phone = phone;
        this.display = display;
        this.thumbnail_link = thumbnail_link;
        this.original_link = original_link;
        this.data1 = data1;
    }
    @Generated(hash = 393979869)
    public ContactEntity() {
    }
    public String getUserName() {
        return this.userName;
    }
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getNickName() {
        return this.nickName;
    }
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public int getMute() {
        return this.mute;
    }
    public void setMute(int mute) {
        this.mute = mute;
    }
    public String getPhone() {
        return this.phone;
    }
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getDisplay() {
        return this.display;
    }
    public void setDisplay(String display) {
        this.display = display;
    }
    public String getThumbnail_link() {
        return this.thumbnail_link;
    }
    public void setThumbnail_link(String thumbnail_link) {
        this.thumbnail_link = thumbnail_link;
    }
    public String getOriginal_link() {
        return this.original_link;
    }
    public void setOriginal_link(String original_link) {
        this.original_link = original_link;
    }
    public String getData1() {
        return this.data1;
    }
    public void setData1(String data1) {
        this.data1 = data1;
    }


    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.userName);
        dest.writeString(this.nickName);
        dest.writeInt(this.mute);
        dest.writeString(this.phone);
        dest.writeString(this.display);
        dest.writeString(this.thumbnail_link);
        dest.writeString(this.original_link);
        dest.writeString(this.data1);
    }

    protected ContactEntity(Parcel in) {
        this.userName = in.readString();
        this.nickName = in.readString();
        this.mute = in.readInt();
        this.phone = in.readString();
        this.display = in.readString();
        this.thumbnail_link=in.readString();
        this.original_link=in.readString();
        this.data1 = in.readString();
    }

    public static final Parcelable.Creator<ContactEntity> CREATOR = new Parcelable.Creator<ContactEntity>() {
        @Override
        public ContactEntity createFromParcel(Parcel source) {
            return new ContactEntity(source);
        }

        @Override
        public ContactEntity[] newArray(int size) {
            return new ContactEntity[size];
        }
    };

}
