package com.littlec.sdk.database.entity;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "ExcTask".
 */
@Entity
public class ExcTaskDBEntity {
    @Id
    private String TaskId;
    private Long FirstSendTime;
    private Integer SendCount;
    private Integer ExcType;
    private Long msgID;
    @Generated(hash = 641377261)
    public ExcTaskDBEntity(String TaskId, Long FirstSendTime, Integer SendCount,
            Integer ExcType, Long msgID) {
        this.TaskId = TaskId;
        this.FirstSendTime = FirstSendTime;
        this.SendCount = SendCount;
        this.ExcType = ExcType;
        this.msgID = msgID;
    }
    @Generated(hash = 170491355)
    public ExcTaskDBEntity() {
    }
    public String getTaskId() {
        return this.TaskId;
    }
    public void setTaskId(String TaskId) {
        this.TaskId = TaskId;
    }
    public Long getFirstSendTime() {
        return this.FirstSendTime;
    }
    public void setFirstSendTime(Long FirstSendTime) {
        this.FirstSendTime = FirstSendTime;
    }
    public Integer getSendCount() {
        return this.SendCount;
    }
    public void setSendCount(Integer SendCount) {
        this.SendCount = SendCount;
    }
    public Integer getExcType() {
        return this.ExcType;
    }
    public void setExcType(Integer ExcType) {
        this.ExcType = ExcType;
    }
    public Long getMsgID() {
        return this.msgID;
    }
    public void setMsgID(Long msgID) {
        this.msgID = msgID;
    }
}
