package com.littlec.sdk.database.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "FriendReq".
 */
@Entity
public class FriendReqDBEntity implements Parcelable{
    @Id
    private String fromUserName;
    private String fromNick;
    private String regId;
    private Integer reqType;
    private String remark;
    private Long modified;
    private Integer contactstatus;
    private Boolean isDeal;
    @Generated(hash = 2069815534)
    public FriendReqDBEntity(String fromUserName, String fromNick, String regId,
            Integer reqType, String remark, Long modified, Integer contactstatus,
            Boolean isDeal) {
        this.fromUserName = fromUserName;
        this.fromNick = fromNick;
        this.regId = regId;
        this.reqType = reqType;
        this.remark = remark;
        this.modified = modified;
        this.contactstatus = contactstatus;
        this.isDeal = isDeal;
    }
    @Generated(hash = 809583284)
    public FriendReqDBEntity() {
    }
    public String getFromUserName() {
        return this.fromUserName;
    }
    public void setFromUserName(String fromUserName) {
        this.fromUserName = fromUserName;
    }
    public String getFromNick() {
        return this.fromNick;
    }
    public void setFromNick(String fromNick) {
        this.fromNick = fromNick;
    }
    public String getRegId() {
        return this.regId;
    }
    public void setRegId(String regId) {
        this.regId = regId;
    }
    public Integer getReqType() {
        return this.reqType;
    }
    public void setReqType(Integer reqType) {
        this.reqType = reqType;
    }
    public String getRemark() {
        return this.remark;
    }
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Long getModified() {
        return this.modified;
    }
    public void setModified(Long modified) {
        this.modified = modified;
    }
    public Integer getContactstatus() {
        return this.contactstatus;
    }
    public void setContactstatus(Integer contactstatus) {
        this.contactstatus = contactstatus;
    }
    public Boolean getIsDeal() {
        return this.isDeal;
    }
    public void setIsDeal(Boolean isDeal) {
        this.isDeal = isDeal;
    }

// KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.fromUserName);
        dest.writeString(this.fromNick);
        dest.writeString(this.regId);
        dest.writeValue(this.reqType);
        dest.writeString(this.remark);
        dest.writeValue(this.modified);
        dest.writeValue(this.contactstatus);
        dest.writeValue(this.isDeal);
    }

    protected FriendReqDBEntity(Parcel in) {
        this.fromUserName = in.readString();
        this.fromNick = in.readString();
        this.regId = in.readString();
        this.reqType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.remark = in.readString();
        this.modified = (Long) in.readValue(Long.class.getClassLoader());
        this.contactstatus = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isDeal=(Boolean)in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<FriendReqDBEntity> CREATOR = new Parcelable.Creator<FriendReqDBEntity>() {
        @Override
        public FriendReqDBEntity createFromParcel(Parcel source) {
            return new FriendReqDBEntity(source);
        }

        @Override
        public FriendReqDBEntity[] newArray(int size) {
            return new FriendReqDBEntity[size];
        }
    };
}
