package com.littlec.sdk.database.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "Media".
 */
@Entity
public class MediaEntity implements Parcelable{
    @Id
    private Long id;
    private String content;
    private String thumbPath;
    private String fileName;
    private long fileLength;
    private Boolean isOrigin;
    private String originalLink;
    private String largeLink;
    private String middleLink;
    private String smallLink;
    private int duration;
    private double latitude;
    private double longitude;
    private String address;
    private String locationDes;
    private String title;
    private String webSite;
    private String summary;
    private String iconUrl;
    private String data1;
    @Generated(hash = 745354814)
    public MediaEntity(Long id, String content, String thumbPath, String fileName,
            long fileLength, Boolean isOrigin, String originalLink,
            String largeLink, String middleLink, String smallLink, int duration,
            double latitude, double longitude, String address, String locationDes,
            String title, String webSite, String summary, String iconUrl,
            String data1) {
        this.id = id;
        this.content = content;
        this.thumbPath = thumbPath;
        this.fileName = fileName;
        this.fileLength = fileLength;
        this.isOrigin = isOrigin;
        this.originalLink = originalLink;
        this.largeLink = largeLink;
        this.middleLink = middleLink;
        this.smallLink = smallLink;
        this.duration = duration;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.locationDes = locationDes;
        this.title = title;
        this.webSite = webSite;
        this.summary = summary;
        this.iconUrl = iconUrl;
        this.data1 = data1;
    }
    @Generated(hash = 887223317)
    public MediaEntity() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getContent() {
        return this.content;
    }
    public void setContent(String content) {
        this.content = content;
    }
    public String getThumbPath() {
        return this.thumbPath;
    }
    public void setThumbPath(String thumbPath) {
        this.thumbPath = thumbPath;
    }
    public String getFileName() {
        return this.fileName;
    }
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public long getFileLength() {
        return this.fileLength;
    }
    public void setFileLength(long fileLength) {
        this.fileLength = fileLength;
    }
    public Boolean getIsOrigin() {
        return this.isOrigin;
    }
    public void setIsOrigin(Boolean isOrigin) {
        this.isOrigin = isOrigin;
    }
    public String getOriginalLink() {
        return this.originalLink;
    }
    public void setOriginalLink(String originalLink) {
        this.originalLink = originalLink;
    }
    public String getLargeLink() {
        return this.largeLink;
    }
    public void setLargeLink(String largeLink) {
        this.largeLink = largeLink;
    }
    public String getMiddleLink() {
        return this.middleLink;
    }
    public void setMiddleLink(String middleLink) {
        this.middleLink = middleLink;
    }
    public String getSmallLink() {
        return this.smallLink;
    }
    public void setSmallLink(String smallLink) {
        this.smallLink = smallLink;
    }
    public int getDuration() {
        return this.duration;
    }
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public double getLatitude() {
        return this.latitude;
    }
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public String getLocationDes() {
        return this.locationDes;
    }
    public void setLocationDes(String locationDes) {
        this.locationDes = locationDes;
    }
    public String getTitle() {
        return this.title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getWebSite() {
        return this.webSite;
    }
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }
    public String getSummary() {
        return this.summary;
    }
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getIconUrl() {
        return this.iconUrl;
    }
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }
    public String getData1() {
        return this.data1;
    }
    public void setData1(String data1) {
        this.data1 = data1;
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.content);
        dest.writeString(this.thumbPath);
        dest.writeString(this.fileName);
        dest.writeLong(this.fileLength);
        dest.writeString(this.originalLink);
        dest.writeString(this.largeLink);
        dest.writeString(this.middleLink);
        dest.writeString(this.smallLink);
        dest.writeInt(this.duration);
        dest.writeDouble(this.latitude);
        dest.writeDouble(this.longitude);
        dest.writeString(this.address);
        dest.writeString(this.locationDes);
        dest.writeString(this.title);
        dest.writeString(this.webSite);
        dest.writeString(this.summary);
        dest.writeString(this.iconUrl);
        dest.writeString(this.data1);
    }

    protected MediaEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.content = in.readString();
        this.thumbPath = in.readString();
        this.fileName = in.readString();
        this.fileLength = in.readLong();
        this.originalLink = in.readString();
        this.largeLink = in.readString();
        this.middleLink = in.readString();
        this.smallLink = in.readString();
        this.duration = in.readInt();
        this.latitude = in.readDouble();
        this.longitude = in.readDouble();
        this.address=in.readString();
        this.locationDes = in.readString();
        this.title = in.readString();
        this.webSite = in.readString();
        this.summary = in.readString();
        this.iconUrl = in.readString();
        this.data1 = in.readString();
    }

    public static final Parcelable.Creator<MediaEntity> CREATOR = new Parcelable.Creator<MediaEntity>() {
        @Override
        public MediaEntity createFromParcel(Parcel source) {
            return new MediaEntity(source);
        }

        @Override
        public MediaEntity[] newArray(int size) {
            return new MediaEntity[size];
        }
    };
}
